const PHOTO_DESCRIPTION_COUNT = 25;
const MIN_VALUE_OF_LIKES = 15;
const MAX_VALUE_OF_LIKES = 200;
const MIN_VALUE_AVATAR = 1;
const MAX_VALUE_AVATAR = 6;
const MAX_VALUE_OF_COMMENTS = 5;

export {PHOTO_DESCRIPTION_COUNT, MIN_VALUE_OF_LIKES, MAX_VALUE_OF_LIKES, MIN_VALUE_AVATAR, MAX_VALUE_AVATAR, MAX_VALUE_OF_COMMENTS};
